// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: daemon/provider_service.proto

package daemon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderServiceCapability int32

const (
	ProviderServiceCapability_PROVIDER_SERVICE_CAPABILITY_UNSPECIFIED  ProviderServiceCapability = 0
	ProviderServiceCapability_PROVIDER_SERVICE_CAPABILITY_LIST         ProviderServiceCapability = 1
	ProviderServiceCapability_PROVIDER_SERVICE_CAPABILITY_SUBSCRIBE    ProviderServiceCapability = 2
	ProviderServiceCapability_PROVIDER_SERVICE_CAPABILITY_REFRESH      ProviderServiceCapability = 3
	ProviderServiceCapability_PROVIDER_SERVICE_CAPABILITY_HEALTH_CHECK ProviderServiceCapability = 4
)

// Enum value maps for ProviderServiceCapability.
var (
	ProviderServiceCapability_name = map[int32]string{
		0: "PROVIDER_SERVICE_CAPABILITY_UNSPECIFIED",
		1: "PROVIDER_SERVICE_CAPABILITY_LIST",
		2: "PROVIDER_SERVICE_CAPABILITY_SUBSCRIBE",
		3: "PROVIDER_SERVICE_CAPABILITY_REFRESH",
		4: "PROVIDER_SERVICE_CAPABILITY_HEALTH_CHECK",
	}
	ProviderServiceCapability_value = map[string]int32{
		"PROVIDER_SERVICE_CAPABILITY_UNSPECIFIED":  0,
		"PROVIDER_SERVICE_CAPABILITY_LIST":         1,
		"PROVIDER_SERVICE_CAPABILITY_SUBSCRIBE":    2,
		"PROVIDER_SERVICE_CAPABILITY_REFRESH":      3,
		"PROVIDER_SERVICE_CAPABILITY_HEALTH_CHECK": 4,
	}
)

func (x ProviderServiceCapability) Enum() *ProviderServiceCapability {
	p := new(ProviderServiceCapability)
	*p = x
	return p
}

func (x ProviderServiceCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderServiceCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_provider_service_proto_enumTypes[0].Descriptor()
}

func (ProviderServiceCapability) Type() protoreflect.EnumType {
	return &file_daemon_provider_service_proto_enumTypes[0]
}

func (x ProviderServiceCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderServiceCapability.Descriptor instead.
func (ProviderServiceCapability) EnumDescriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{0}
}

type ProviderHealthState int32

const (
	ProviderHealthState_PROVIDER_HEALTH_STATE_UNSPECIFIED ProviderHealthState = 0
	ProviderHealthState_PROVIDER_HEALTH_STATE_UNKNOWN     ProviderHealthState = 1
	ProviderHealthState_PROVIDER_HEALTH_STATE_REACHABLE   ProviderHealthState = 2
	ProviderHealthState_PROVIDER_HEALTH_STATE_UNREACHABLE ProviderHealthState = 3
)

// Enum value maps for ProviderHealthState.
var (
	ProviderHealthState_name = map[int32]string{
		0: "PROVIDER_HEALTH_STATE_UNSPECIFIED",
		1: "PROVIDER_HEALTH_STATE_UNKNOWN",
		2: "PROVIDER_HEALTH_STATE_REACHABLE",
		3: "PROVIDER_HEALTH_STATE_UNREACHABLE",
	}
	ProviderHealthState_value = map[string]int32{
		"PROVIDER_HEALTH_STATE_UNSPECIFIED": 0,
		"PROVIDER_HEALTH_STATE_UNKNOWN":     1,
		"PROVIDER_HEALTH_STATE_REACHABLE":   2,
		"PROVIDER_HEALTH_STATE_UNREACHABLE": 3,
	}
)

func (x ProviderHealthState) Enum() *ProviderHealthState {
	p := new(ProviderHealthState)
	*p = x
	return p
}

func (x ProviderHealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderHealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_daemon_provider_service_proto_enumTypes[1].Descriptor()
}

func (ProviderHealthState) Type() protoreflect.EnumType {
	return &file_daemon_provider_service_proto_enumTypes[1]
}

func (x ProviderHealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderHealthState.Descriptor instead.
func (ProviderHealthState) EnumDescriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{1}
}

type ProviderServiceInfo struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	ProtocolVersion uint32                      `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Capabilities    []ProviderServiceCapability `protobuf:"varint,2,rep,packed,name=capabilities,proto3,enum=daemon.ProviderServiceCapability" json:"capabilities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProviderServiceInfo) Reset() {
	*x = ProviderServiceInfo{}
	mi := &file_daemon_provider_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderServiceInfo) ProtoMessage() {}

func (x *ProviderServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderServiceInfo.ProtoReflect.Descriptor instead.
func (*ProviderServiceInfo) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{0}
}

func (x *ProviderServiceInfo) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ProviderServiceInfo) GetCapabilities() []ProviderServiceCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type GetProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderTag   string                 `protobuf:"bytes,1,opt,name=provider_tag,json=providerTag,proto3" json:"provider_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderRequest) Reset() {
	*x = GetProviderRequest{}
	mi := &file_daemon_provider_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderRequest) ProtoMessage() {}

func (x *GetProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderRequest.ProtoReflect.Descriptor instead.
func (*GetProviderRequest) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProviderRequest) GetProviderTag() string {
	if x != nil {
		return x.ProviderTag
	}
	return ""
}

type ProviderActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderTag   string                 `protobuf:"bytes,1,opt,name=provider_tag,json=providerTag,proto3" json:"provider_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderActionRequest) Reset() {
	*x = ProviderActionRequest{}
	mi := &file_daemon_provider_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderActionRequest) ProtoMessage() {}

func (x *ProviderActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderActionRequest.ProtoReflect.Descriptor instead.
func (*ProviderActionRequest) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProviderActionRequest) GetProviderTag() string {
	if x != nil {
		return x.ProviderTag
	}
	return ""
}

type ProviderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Providers     []*Provider            `protobuf:"bytes,3,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderList) Reset() {
	*x = ProviderList{}
	mi := &file_daemon_provider_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderList) ProtoMessage() {}

func (x *ProviderList) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderList.ProtoReflect.Descriptor instead.
func (*ProviderList) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{3}
}

func (x *ProviderList) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ProviderList) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ProviderList) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type Provider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UpdatedAtMs   int64                  `protobuf:"varint,3,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	Capabilities  *ProviderCapabilities  `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Subscription  *SubscriptionInfo      `protobuf:"bytes,5,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Nodes         []*ProviderNode        `protobuf:"bytes,6,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_daemon_provider_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{4}
}

func (x *Provider) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *Provider) GetCapabilities() *ProviderCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Provider) GetSubscription() *SubscriptionInfo {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *Provider) GetNodes() []*ProviderNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ProviderCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CanRefresh          bool                   `protobuf:"varint,1,opt,name=can_refresh,json=canRefresh,proto3" json:"can_refresh,omitempty"`
	CanHealthCheck      bool                   `protobuf:"varint,2,opt,name=can_health_check,json=canHealthCheck,proto3" json:"can_health_check,omitempty"`
	HasSubscriptionInfo bool                   `protobuf:"varint,3,opt,name=has_subscription_info,json=hasSubscriptionInfo,proto3" json:"has_subscription_info,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProviderCapabilities) Reset() {
	*x = ProviderCapabilities{}
	mi := &file_daemon_provider_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderCapabilities) ProtoMessage() {}

func (x *ProviderCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderCapabilities.ProtoReflect.Descriptor instead.
func (*ProviderCapabilities) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{5}
}

func (x *ProviderCapabilities) GetCanRefresh() bool {
	if x != nil {
		return x.CanRefresh
	}
	return false
}

func (x *ProviderCapabilities) GetCanHealthCheck() bool {
	if x != nil {
		return x.CanHealthCheck
	}
	return false
}

func (x *ProviderCapabilities) GetHasSubscriptionInfo() bool {
	if x != nil {
		return x.HasSubscriptionInfo
	}
	return false
}

type SubscriptionInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UploadBytes     int64                  `protobuf:"varint,1,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes   int64                  `protobuf:"varint,2,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	TotalBytes      int64                  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	ExpireAtSeconds int64                  `protobuf:"varint,4,opt,name=expire_at_seconds,json=expireAtSeconds,proto3" json:"expire_at_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscriptionInfo) Reset() {
	*x = SubscriptionInfo{}
	mi := &file_daemon_provider_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionInfo) ProtoMessage() {}

func (x *SubscriptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionInfo.ProtoReflect.Descriptor instead.
func (*SubscriptionInfo) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{6}
}

func (x *SubscriptionInfo) GetUploadBytes() int64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *SubscriptionInfo) GetDownloadBytes() int64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

func (x *SubscriptionInfo) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *SubscriptionInfo) GetExpireAtSeconds() int64 {
	if x != nil {
		return x.ExpireAtSeconds
	}
	return 0
}

type ProviderNodeHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ProviderHealthState    `protobuf:"varint,1,opt,name=state,proto3,enum=daemon.ProviderHealthState" json:"state,omitempty"`
	DelayMs       uint32                 `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	CheckedAtMs   int64                  `protobuf:"varint,3,opt,name=checked_at_ms,json=checkedAtMs,proto3" json:"checked_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderNodeHealth) Reset() {
	*x = ProviderNodeHealth{}
	mi := &file_daemon_provider_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderNodeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderNodeHealth) ProtoMessage() {}

func (x *ProviderNodeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderNodeHealth.ProtoReflect.Descriptor instead.
func (*ProviderNodeHealth) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{7}
}

func (x *ProviderNodeHealth) GetState() ProviderHealthState {
	if x != nil {
		return x.State
	}
	return ProviderHealthState_PROVIDER_HEALTH_STATE_UNSPECIFIED
}

func (x *ProviderNodeHealth) GetDelayMs() uint32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *ProviderNodeHealth) GetCheckedAtMs() int64 {
	if x != nil {
		return x.CheckedAtMs
	}
	return 0
}

type ProviderNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Networks      []string               `protobuf:"bytes,3,rep,name=networks,proto3" json:"networks,omitempty"`
	Health        *ProviderNodeHealth    `protobuf:"bytes,4,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderNode) Reset() {
	*x = ProviderNode{}
	mi := &file_daemon_provider_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderNode) ProtoMessage() {}

func (x *ProviderNode) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderNode.ProtoReflect.Descriptor instead.
func (*ProviderNode) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{8}
}

func (x *ProviderNode) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ProviderNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProviderNode) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *ProviderNode) GetHealth() *ProviderNodeHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

type ProviderActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Provider      *Provider              `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderActionResult) Reset() {
	*x = ProviderActionResult{}
	mi := &file_daemon_provider_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderActionResult) ProtoMessage() {}

func (x *ProviderActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderActionResult.ProtoReflect.Descriptor instead.
func (*ProviderActionResult) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderActionResult) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ProviderActionResult) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ProviderActionResult) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type ProviderHealthCheckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Provider      *Provider              `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Results       []*ProviderNodeResult  `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderHealthCheckResult) Reset() {
	*x = ProviderHealthCheckResult{}
	mi := &file_daemon_provider_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHealthCheckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHealthCheckResult) ProtoMessage() {}

func (x *ProviderHealthCheckResult) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHealthCheckResult.ProtoReflect.Descriptor instead.
func (*ProviderHealthCheckResult) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderHealthCheckResult) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ProviderHealthCheckResult) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ProviderHealthCheckResult) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *ProviderHealthCheckResult) GetResults() []*ProviderNodeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProviderNodeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeTag       string                 `protobuf:"bytes,1,opt,name=node_tag,json=nodeTag,proto3" json:"node_tag,omitempty"`
	Health        *ProviderNodeHealth    `protobuf:"bytes,2,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderNodeResult) Reset() {
	*x = ProviderNodeResult{}
	mi := &file_daemon_provider_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderNodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderNodeResult) ProtoMessage() {}

func (x *ProviderNodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_daemon_provider_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderNodeResult.ProtoReflect.Descriptor instead.
func (*ProviderNodeResult) Descriptor() ([]byte, []int) {
	return file_daemon_provider_service_proto_rawDescGZIP(), []int{11}
}

func (x *ProviderNodeResult) GetNodeTag() string {
	if x != nil {
		return x.NodeTag
	}
	return ""
}

func (x *ProviderNodeResult) GetHealth() *ProviderNodeHealth {
	if x != nil {
		return x.Health
	}
	return nil
}

var File_daemon_provider_service_proto protoreflect.FileDescriptor

const file_daemon_provider_service_proto_rawDesc = "" +
	"\n" +
	"\x1ddaemon/provider_service.proto\x12\x06daemon\x1a\x1bgoogle/protobuf/empty.proto\"\x8d\x01\n" +
	"\x13ProviderServiceInfo\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12E\n" +
	"\fcapabilities\x18\x02 \x03(\x0e2!.daemon.ProviderServiceCapabilityR\fcapabilitiesJ\x04\b\x03\x10\x10\"=\n" +
	"\x12GetProviderRequest\x12!\n" +
	"\fprovider_tag\x18\x01 \x01(\tR\vproviderTagJ\x04\b\x02\x10\x10\"@\n" +
	"\x15ProviderActionRequest\x12!\n" +
	"\fprovider_tag\x18\x01 \x01(\tR\vproviderTagJ\x04\b\x02\x10\x10\"\x81\x01\n" +
	"\fProviderList\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12.\n" +
	"\tproviders\x18\x03 \x03(\v2\x10.daemon.ProviderR\tprovidersJ\x04\b\x04\x10\x10\"\x86\x02\n" +
	"\bProvider\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\rupdated_at_ms\x18\x03 \x01(\x03R\vupdatedAtMs\x12@\n" +
	"\fcapabilities\x18\x04 \x01(\v2\x1c.daemon.ProviderCapabilitiesR\fcapabilities\x12<\n" +
	"\fsubscription\x18\x05 \x01(\v2\x18.daemon.SubscriptionInfoR\fsubscription\x12*\n" +
	"\x05nodes\x18\x06 \x03(\v2\x14.daemon.ProviderNodeR\x05nodesJ\x04\b\a\x10 \"\x9b\x01\n" +
	"\x14ProviderCapabilities\x12\x1f\n" +
	"\vcan_refresh\x18\x01 \x01(\bR\n" +
	"canRefresh\x12(\n" +
	"\x10can_health_check\x18\x02 \x01(\bR\x0ecanHealthCheck\x122\n" +
	"\x15has_subscription_info\x18\x03 \x01(\bR\x13hasSubscriptionInfoJ\x04\b\x04\x10\x10\"\xaf\x01\n" +
	"\x10SubscriptionInfo\x12!\n" +
	"\fupload_bytes\x18\x01 \x01(\x03R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\x02 \x01(\x03R\rdownloadBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x03 \x01(\x03R\n" +
	"totalBytes\x12*\n" +
	"\x11expire_at_seconds\x18\x04 \x01(\x03R\x0fexpireAtSecondsJ\x04\b\x05\x10\x10\"\x8c\x01\n" +
	"\x12ProviderNodeHealth\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1b.daemon.ProviderHealthStateR\x05state\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\rR\adelayMs\x12\"\n" +
	"\rchecked_at_ms\x18\x03 \x01(\x03R\vcheckedAtMsJ\x04\b\x04\x10\x10\"\x8a\x01\n" +
	"\fProviderNode\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bnetworks\x18\x03 \x03(\tR\bnetworks\x122\n" +
	"\x06health\x18\x04 \x01(\v2\x1a.daemon.ProviderNodeHealthR\x06healthJ\x04\b\x05\x10\x10\"\x87\x01\n" +
	"\x14ProviderActionResult\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12,\n" +
	"\bprovider\x18\x03 \x01(\v2\x10.daemon.ProviderR\bproviderJ\x04\b\x04\x10\x10\"\xc2\x01\n" +
	"\x19ProviderHealthCheckResult\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12,\n" +
	"\bprovider\x18\x03 \x01(\v2\x10.daemon.ProviderR\bprovider\x124\n" +
	"\aresults\x18\x04 \x03(\v2\x1a.daemon.ProviderNodeResultR\aresultsJ\x04\b\x05\x10\x10\"i\n" +
	"\x12ProviderNodeResult\x12\x19\n" +
	"\bnode_tag\x18\x01 \x01(\tR\anodeTag\x122\n" +
	"\x06health\x18\x02 \x01(\v2\x1a.daemon.ProviderNodeHealthR\x06healthJ\x04\b\x03\x10\x10*\xf0\x01\n" +
	"\x19ProviderServiceCapability\x12+\n" +
	"'PROVIDER_SERVICE_CAPABILITY_UNSPECIFIED\x10\x00\x12$\n" +
	" PROVIDER_SERVICE_CAPABILITY_LIST\x10\x01\x12)\n" +
	"%PROVIDER_SERVICE_CAPABILITY_SUBSCRIBE\x10\x02\x12'\n" +
	"#PROVIDER_SERVICE_CAPABILITY_REFRESH\x10\x03\x12,\n" +
	"(PROVIDER_SERVICE_CAPABILITY_HEALTH_CHECK\x10\x04*\xab\x01\n" +
	"\x13ProviderHealthState\x12%\n" +
	"!PROVIDER_HEALTH_STATE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dPROVIDER_HEALTH_STATE_UNKNOWN\x10\x01\x12#\n" +
	"\x1fPROVIDER_HEALTH_STATE_REACHABLE\x10\x02\x12%\n" +
	"!PROVIDER_HEALTH_STATE_UNREACHABLE\x10\x032\xcf\x03\n" +
	"\x0fProviderService\x12G\n" +
	"\x0eGetServiceInfo\x12\x16.google.protobuf.Empty\x1a\x1b.daemon.ProviderServiceInfo\"\x00\x12?\n" +
	"\rListProviders\x12\x16.google.protobuf.Empty\x1a\x14.daemon.ProviderList\"\x00\x12=\n" +
	"\vGetProvider\x12\x1a.daemon.GetProviderRequest\x1a\x10.daemon.Provider\"\x00\x12F\n" +
	"\x12SubscribeProviders\x12\x16.google.protobuf.Empty\x1a\x14.daemon.ProviderList\"\x000\x01\x12P\n" +
	"\x0fRefreshProvider\x12\x1d.daemon.ProviderActionRequest\x1a\x1c.daemon.ProviderActionResult\"\x00\x12Y\n" +
	"\x13HealthCheckProvider\x12\x1d.daemon.ProviderActionRequest\x1a!.daemon.ProviderHealthCheckResult\"\x00B%Z#github.com/sagernet/sing-box/daemonb\x06proto3"

var (
	file_daemon_provider_service_proto_rawDescOnce sync.Once
	file_daemon_provider_service_proto_rawDescData []byte
)

func file_daemon_provider_service_proto_rawDescGZIP() []byte {
	file_daemon_provider_service_proto_rawDescOnce.Do(func() {
		file_daemon_provider_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_daemon_provider_service_proto_rawDesc), len(file_daemon_provider_service_proto_rawDesc)))
	})
	return file_daemon_provider_service_proto_rawDescData
}

var file_daemon_provider_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_daemon_provider_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_daemon_provider_service_proto_goTypes = []any{
	(ProviderServiceCapability)(0),    // 0: daemon.ProviderServiceCapability
	(ProviderHealthState)(0),          // 1: daemon.ProviderHealthState
	(*ProviderServiceInfo)(nil),       // 2: daemon.ProviderServiceInfo
	(*GetProviderRequest)(nil),        // 3: daemon.GetProviderRequest
	(*ProviderActionRequest)(nil),     // 4: daemon.ProviderActionRequest
	(*ProviderList)(nil),              // 5: daemon.ProviderList
	(*Provider)(nil),                  // 6: daemon.Provider
	(*ProviderCapabilities)(nil),      // 7: daemon.ProviderCapabilities
	(*SubscriptionInfo)(nil),          // 8: daemon.SubscriptionInfo
	(*ProviderNodeHealth)(nil),        // 9: daemon.ProviderNodeHealth
	(*ProviderNode)(nil),              // 10: daemon.ProviderNode
	(*ProviderActionResult)(nil),      // 11: daemon.ProviderActionResult
	(*ProviderHealthCheckResult)(nil), // 12: daemon.ProviderHealthCheckResult
	(*ProviderNodeResult)(nil),        // 13: daemon.ProviderNodeResult
	(*emptypb.Empty)(nil),             // 14: google.protobuf.Empty
}
var file_daemon_provider_service_proto_depIdxs = []int32{
	0,  // 0: daemon.ProviderServiceInfo.capabilities:type_name -> daemon.ProviderServiceCapability
	6,  // 1: daemon.ProviderList.providers:type_name -> daemon.Provider
	7,  // 2: daemon.Provider.capabilities:type_name -> daemon.ProviderCapabilities
	8,  // 3: daemon.Provider.subscription:type_name -> daemon.SubscriptionInfo
	10, // 4: daemon.Provider.nodes:type_name -> daemon.ProviderNode
	1,  // 5: daemon.ProviderNodeHealth.state:type_name -> daemon.ProviderHealthState
	9,  // 6: daemon.ProviderNode.health:type_name -> daemon.ProviderNodeHealth
	6,  // 7: daemon.ProviderActionResult.provider:type_name -> daemon.Provider
	6,  // 8: daemon.ProviderHealthCheckResult.provider:type_name -> daemon.Provider
	13, // 9: daemon.ProviderHealthCheckResult.results:type_name -> daemon.ProviderNodeResult
	9,  // 10: daemon.ProviderNodeResult.health:type_name -> daemon.ProviderNodeHealth
	14, // 11: daemon.ProviderService.GetServiceInfo:input_type -> google.protobuf.Empty
	14, // 12: daemon.ProviderService.ListProviders:input_type -> google.protobuf.Empty
	3,  // 13: daemon.ProviderService.GetProvider:input_type -> daemon.GetProviderRequest
	14, // 14: daemon.ProviderService.SubscribeProviders:input_type -> google.protobuf.Empty
	4,  // 15: daemon.ProviderService.RefreshProvider:input_type -> daemon.ProviderActionRequest
	4,  // 16: daemon.ProviderService.HealthCheckProvider:input_type -> daemon.ProviderActionRequest
	2,  // 17: daemon.ProviderService.GetServiceInfo:output_type -> daemon.ProviderServiceInfo
	5,  // 18: daemon.ProviderService.ListProviders:output_type -> daemon.ProviderList
	6,  // 19: daemon.ProviderService.GetProvider:output_type -> daemon.Provider
	5,  // 20: daemon.ProviderService.SubscribeProviders:output_type -> daemon.ProviderList
	11, // 21: daemon.ProviderService.RefreshProvider:output_type -> daemon.ProviderActionResult
	12, // 22: daemon.ProviderService.HealthCheckProvider:output_type -> daemon.ProviderHealthCheckResult
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_daemon_provider_service_proto_init() }
func file_daemon_provider_service_proto_init() {
	if File_daemon_provider_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_daemon_provider_service_proto_rawDesc), len(file_daemon_provider_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_daemon_provider_service_proto_goTypes,
		DependencyIndexes: file_daemon_provider_service_proto_depIdxs,
		EnumInfos:         file_daemon_provider_service_proto_enumTypes,
		MessageInfos:      file_daemon_provider_service_proto_msgTypes,
	}.Build()
	File_daemon_provider_service_proto = out.File
	file_daemon_provider_service_proto_goTypes = nil
	file_daemon_provider_service_proto_depIdxs = nil
}
